import Head from 'next/head'
import Box5 from '../components/Box5'

export default function EventMotion() {
  return (
    <>
      <Head>
        <title>Framer Motion</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box5 />
    </>
  )
}
